import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "../css/globals.css";
import "../css/euclidCircularA.css";
import Header from "./header";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white dark:bg-gray-900">
      <body className={`font-euclidCircularA ` + inter.className}>
        <div className="mt-5 bg-white dark:bg-gray-900 text-black dark:text-gray-300">
          <Header />
          <main className="flex flex-col gap-8 row-start-2 items-center sm:items-center justify-center">
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
        </div>
      </body>
    </html>
  );
}
